









export class GetPage{
	public paragraphes:any;
	
	constructor(){
		
		this.paragraphes={"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacus urna, pulvinar non massa et, sodales scelerisque orci. Proin quis tellus eros. Curabitur finibus est id nisi porttitor, et pharetra mi efficitur. Vivamus consectetur, tellus id hendrerit varius, leo tortor ultricies dolor, id lacinia elit leo nec dui. Nunc vulputate felis augue, nec placerat quam blandit ac. Aenean ultrices nibh viverra purus pulvinar, interdum euismod purus luctus. Quisque vulputate sed orci sed posuere. Vivamus feugiat convallis urna, quis tincidunt magna egestas sed. Nulla augue purus, maximus sed porttitor eu, scelerisque et enim.",
		"Aenean cursus ligula nec dignissim eleifend. Sed ut iaculis odio. Cras in leo ut massa tincidunt molestie. Fusce eget ultrices nibh. Vestibulum finibus ipsum iaculis, laoreet odio non, posuere tortor. Nulla nec ligula fringilla mauris porta sollicitudin non at sapien. Sed ac leo a mauris eleifend volutpat. Aenean suscipit leo est, eu porta risus sollicitudin et.",
		"In lobortis ultrices dui. Sed dapibus libero vehicula efficitur euismod. Nam eu vestibulum ex, ut tristique orci. Donec vitae tellus nisl. Ut sollicitudin consectetur risus, nec vulputate purus accumsan non. Suspendisse eget leo leo. Nam consequat tincidunt efficitur. Proin elementum facilisis nisl vitae tincidunt. Morbi volutpat convallis nibh, at eleifend augue interdum ut. Nam mollis mi enim, ac aliquam est ullamcorper iaculis. Vestibulum ante mauris, interdum ac mauris sed, tempor vehicula felis. Etiam facilisis tellus a lorem scelerisque accumsan. Aenean dui lorem, mollis quis turpis at, vehicula porta mi.",
		"Donec sit amet molestie nibh, in mattis nisl. Cras sagittis massa non lectus fermentum, nec consequat orci tincidunt. Integer a nibh vitae arcu vestibulum porttitor. Mauris tellus velit, aliquam vitae lobortis ut, ultricies sed mauris. Mauris nec elit augue. Morbi sed risus et nisl scelerisque imperdiet. Nullam consequat metus ac mauris consequat varius. Sed condimentum hendrerit tortor, a lacinia nisl eleifend non. Duis non luctus urna, a eleifend magna. Aenean finibus accumsan posuere. Sed ac metus pretium libero volutpat auctor ut vel orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam in sapien est. Vivamus lobortis purus velit, faucibus sagittis tellus bibendum id.",
		"Praesent suscipit tristique odio, ac laoreet nunc imperdiet tincidunt. Donec vestibulum justo mauris. Nulla erat quam, accumsan quis rutrum in, eleifend vel ante. Quisque commodo, arcu vel vulputate tempus, quam libero iaculis risus, vitae laoreet justo elit ut libero. Nunc nec odio sit amet quam iaculis lacinia finibus sed ligula. Proin ante elit, bibendum in augue sit amet, lacinia feugiat ipsum. Ut velit lectus, porttitor in purus vel, imperdiet finibus dui. Fusce ac dui tincidunt augue aliquet tempus. Quisque eget ligula nunc. Sed mollis, velit hendrerit tincidunt consequat, sapien ante mattis orci, nec rhoncus justo massa quis felis.",
		"Mauris nunc nisi, vehicula ac arcu quis, rhoncus aliquet mi. Pellentesque nec rutrum sapien, non lobortis erat. Ut sit amet sapien nec justo mattis aliquet. Suspendisse commodo rhoncus diam quis ultrices. Duis vulputate malesuada libero, vel interdum leo ornare vitae. Mauris ut enim est. Nunc in volutpat ante, eu convallis erat. Donec consectetur consectetur mauris in consequat. Nulla vestibulum arcu sed orci feugiat congue. Vivamus sit amet auctor diam. Nam congue rhoncus risus. Ut ut nunc rutrum, aliquam sapien ut, consequat nunc. Duis elementum velit varius efficitur luctus. Mauris venenatis aliquam sem, sed lacinia dolor. Suspendisse sit amet lectus sit amet justo eleifend vehicula non non augue.",
		"Quisque dui tellus, dictum sed sem in, auctor gravida elit. Quisque vehicula aliquet tristique. Vestibulum sit amet ornare justo. Vestibulum elementum eros in felis venenatis, non tempor turpis scelerisque. Donec gravida bibendum lacus a euismod. Aliquam nulla justo, placerat vitae commodo ut, feugiat in nisl. Aenean varius gravida sapien quis fringilla. Vivamus vehicula auctor venenatis. Pellentesque elementum, mauris id fringilla euismod, lorem dolor tincidunt ipsum, a vehicula augue nisi in felis. Vivamus a efficitur odio. Proin velit lacus, luctus in lacinia eget, sodales sit amet elit.",
		"Maecenas tincidunt tellus a libero finibus luctus. Ut consequat rhoncus massa at finibus. Aenean tincidunt accumsan velit, non congue risus maximus eu. In et justo non purus vestibulum imperdiet. Praesent ullamcorper non mi non vehicula. Nulla iaculis volutpat erat, vel varius est iaculis non. Quisque lobortis rhoncus sem, sed ornare sapien laoreet sit amet.",
		"Quisque ac sem a odio ornare tempus at sed purus. Duis posuere bibendum enim eget tincidunt. Sed sodales dignissim nibh. In lacinia aliquam metus, eget accumsan ex. Sed suscipit elit quis justo maximus, vel porttitor odio vestibulum. Etiam sit amet eros in turpis elementum varius ac rutrum dui. Suspendisse id diam ut felis fringilla tristique sit amet eget eros.",
		"In hac habitasse platea dictumst. Pellentesque interdum arcu in tortor sodales, a semper tellus imperdiet. Duis malesuada neque enim, eu tempus ex bibendum non. Proin id eros vel erat mollis iaculis sit amet in nisi. Donec at efficitur magna, eu interdum ipsum. Integer elementum dolor euismod ligula vehicula, nec tristique metus dapibus. Morbi maximus bibendum nisi, sed pretium mauris suscipit in. Donec mi velit, consequat et pellentesque non, convallis id orci. Mauris sit amet enim tellus. Maecenas in libero volutpat, tincidunt arcu non, lobortis libero. Proin a vestibulum diam. Aenean rutrum vulputate quam ac faucibus. Fusce volutpat id nisi nec fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In hac habitasse platea dictumst.",
		"Vestibulum a metus ut mi scelerisque cursus sit amet at dui. Sed a nunc sed leo commodo malesuada. Phasellus eu sagittis sem. Duis ornare leo ut nunc rutrum, vitae finibus tortor varius. Phasellus molestie, enim elementum tincidunt ullamcorper, quam arcu sagittis lorem, sed luctus enim quam id nunc. Curabitur libero purus, pretium sit amet varius ut, ultrices eu erat. Etiam lobortis libero eget enim ornare semper. Donec pretium diam quis dignissim pulvinar. Praesent semper ultricies tristique. Donec ante arcu, pellentesque nec mattis at, tempus eget ligula.",
		"Integer lobortis sapien sit amet libero gravida, sed interdum sem eleifend. Integer justo neque, semper sit amet velit iaculis, hendrerit luctus nisi. Aliquam semper quis nisi vel venenatis. In faucibus sapien sit amet ligula lacinia ultricies. Sed sagittis nisl non arcu efficitur tincidunt. Cras laoreet auctor lacus, vitae fermentum urna porta eget. In metus odio, volutpat at magna nec, aliquam pharetra odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In ut vulputate leo. Duis id aliquam est, in lobortis mauris.",
		"Integer quis egestas massa. Sed faucibus arcu eget pulvinar convallis. Nunc tristique vitae tellus vel ultricies. Sed facilisis est imperdiet viverra sodales. Nullam in malesuada nisl. Aenean sed sapien tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam quis velit leo. Curabitur auctor purus ut varius volutpat. Aliquam ullamcorper, ligula eu molestie elementum, tortor ligula feugiat urna, ut consequat nisl odio eu lacus. Aenean sollicitudin porttitor metus quis dignissim. Nunc nunc velit, facilisis at ipsum nec, suscipit placerat odio. Maecenas convallis varius libero eu gravida. Praesent et metus sit amet odio placerat tincidunt eget non magna. Aliquam gravida sem eu mauris condimentum, et bibendum justo molestie.",
		"Etiam blandit suscipit sapien, in fermentum nisl ornare convallis. Cras auctor urna quis odio malesuada egestas. Sed laoreet hendrerit tortor in dapibus. Vivamus gravida luctus sem eget convallis. Phasellus viverra molestie nisi a euismod. Fusce sed metus sit amet arcu eleifend viverra id at sapien. Fusce tempor nibh eget nisi suscipit porta. Suspendisse faucibus felis eu vulputate dignissim.",
		"Suspendisse commodo fermentum ipsum, ut bibendum metus. Vestibulum porttitor vel nulla a pellentesque. Donec vestibulum felis a tempor pellentesque. Pellentesque urna mi, placerat mollis tristique at, pellentesque eget ex. Sed lobortis nulla et justo rutrum, eu iaculis ex pretium. Suspendisse pretium mollis interdum. Nunc suscipit tristique molestie. Integer tellus nunc, ullamcorper ac commodo vel, porta vel est. Duis sollicitudin leo non rutrum consectetur. Maecenas libero libero, finibus id odio eget, sollicitudin semper quam. Sed finibus, dui ac vulputate sollicitudin, lacus orci porttitor ipsum, non facilisis nulla metus non ligula. Vestibulum eu lorem quis nibh eleifend placerat vitae quis mi.",
		"Nunc sodales neque vitae lorem luctus bibendum. Aliquam posuere nibh massa, quis consequat eros rhoncus et. Donec quis vestibulum dolor, non rhoncus lacus. Duis imperdiet mauris non elit ultricies consectetur. Cras bibendum magna dolor, non consectetur dolor eleifend eleifend. Nulla ornare molestie fermentum. Nam felis eros, accumsan eget gravida a, sollicitudin sit amet enim. Praesent luctus ligula feugiat venenatis viverra. Curabitur vel varius odio. Nullam vitae purus a lorem dictum porttitor eu vitae dolor. Ut a ante scelerisque, porttitor libero et, rutrum erat. Sed blandit convallis velit, eget finibus massa ultricies quis. Vestibulum a arcu sed mi iaculis ullamcorper sed ac nibh.",
		"Suspendisse dapibus porta ligula sed dapibus. Duis dapibus massa id nibh bibendum, a vulputate nisi auctor. Donec mauris nibh, interdum eget nisi vel, aliquet consectetur ante. Nunc imperdiet venenatis libero, eget sollicitudin ex tempor ac. Quisque pulvinar semper nunc non cursus. Pellentesque fringilla ac sapien viverra vestibulum. Phasellus faucibus gravida quam in tincidunt. Ut erat felis, viverra nec gravida vel, convallis non magna. Praesent eu aliquet tellus, ut auctor mauris. Donec dignissim est nulla, ac gravida ligula viverra non. Vivamus ac neque tempor, congue ligula et, fermentum augue. Praesent viverra pharetra nibh, et sagittis ex finibus vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ut nibh ornare, maximus leo a, pulvinar lorem. Nunc congue, elit eget sagittis dictum, eros ligula suscipit erat, in sodales metus justo malesuada sem. Morbi porttitor velit sit amet neque consequat, non iaculis erat aliquet.",
		"Maecenas nulla sapien, scelerisque vitae massa at, blandit scelerisque diam. Proin porta orci a odio dignissim, nec vehicula nisl lacinia. Curabitur luctus velit sed sapien ultrices auctor. Sed porta quis tortor ac vestibulum. Vivamus eget cursus velit, vel porta ex. Aliquam erat volutpat. Praesent scelerisque congue enim, non scelerisque augue malesuada at. Cras quis odio et velit gravida iaculis sed sit amet dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
		"Cras accumsan, magna vitae euismod fermentum, justo ligula aliquet mauris, vitae vestibulum metus nisl ac urna. Sed aliquet egestas orci, sed tempus ante vehicula at. Cras vehicula venenatis est id aliquam. Proin nec ex maximus, cursus ipsum sit amet, vehicula velit. Donec iaculis magna sed ante ornare auctor. Nullam id neque lorem. Cras egestas tortor nunc, ac laoreet justo gravida et. Nunc sollicitudin augue dolor, in porttitor massa vehicula id. Phasellus molestie blandit odio, in laoreet sem mollis vel. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi vel ante porta odio interdum tincidunt vel quis est.",
		"Nunc vitae quam ultrices, accumsan leo a, pharetra ipsum. Donec a lectus nec mi accumsan varius sit amet eu justo. Sed dui tortor, bibendum et ultrices id, interdum ultrices orci. Etiam ultrices, lectus ac placerat vehicula, urna ante pellentesque augue, ac egestas mauris erat in diam. Donec porta nisl quis dolor cursus cursus. Quisque tempus enim eget tellus venenatis ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eu blandit urna. Mauris tincidunt ante nec odio malesuada, at posuere magna venenatis. Vivamus vitae viverra neque. Pellentesque in ante lacus. Donec dictum vestibulum dignissim. Vivamus pulvinar sem quam, pharetra suscipit velit tincidunt non.",
		"Nulla bibendum porttitor diam, nec dapibus risus fringilla posuere. Sed scelerisque sodales odio eu consectetur. Mauris non mi at dui porta pellentesque. Fusce et ligula venenatis, dictum purus fermentum, tristique nibh. Duis suscipit augue ac nunc interdum convallis. Aliquam eu ex non leo ullamcorper posuere. Nullam ut justo posuere, lacinia nulla eu, malesuada velit. Aliquam eu molestie massa, sit amet interdum diam. Nam pellentesque scelerisque sollicitudin. Nunc enim purus, fringilla vitae iaculis et, consequat at justo. Vestibulum in sapien ullamcorper justo placerat luctus. Phasellus vitae felis id nunc porttitor cursus. Aliquam et auctor odio. Ut vitae orci a metus suscipit molestie sit amet sit amet nisl. Donec egestas tortor sit amet magna pretium, egestas tincidunt turpis malesuada. Maecenas nec diam non justo egestas iaculis.",
		"Donec efficitur blandit nibh. Suspendisse risus nunc, porta a aliquam in, aliquet nec nisi. Sed sed lorem fringilla, molestie magna in, ornare nibh. Donec diam tellus, pellentesque lacinia hendrerit eu, tempor a turpis. Praesent tristique venenatis tempor. Morbi risus mi, egestas eget consequat et, accumsan vel urna. Vestibulum aliquet suscipit turpis eget vehicula. Sed mollis ultrices rhoncus. Vestibulum commodo luctus rutrum. Integer ornare enim ac convallis euismod. Aliquam elementum purus iaculis vulputate cursus. Proin quis quam metus. Phasellus eget sapien quis risus scelerisque vulputate.",
		"Cras vitae tortor sodales, faucibus libero non, interdum nunc. Mauris euismod ligula et ligula rutrum, suscipit posuere est consectetur. Sed elit neque, sagittis a blandit sit amet, tristique et nibh. In hac habitasse platea dictumst. Cras vel egestas nunc. Curabitur gravida quam tellus, quis dapibus libero rutrum et. Donec sagittis nulla a nisi laoreet, gravida accumsan odio facilisis. Phasellus et molestie ante. Vivamus commodo tempor urna, interdum commodo massa iaculis et. Etiam neque odio, aliquam et semper eget, commodo non sapien. Nulla lacinia sodales vestibulum. Aliquam eget aliquet augue, vel iaculis sem. Vestibulum et nisl libero. Proin ullamcorper libero vitae ipsum mattis sodales. Donec vel neque sem.",
		"In nec erat eget ex posuere semper. Nullam aliquet volutpat est, a fringilla tellus tempus eget. Nunc viverra risus risus, a placerat tortor pellentesque vitae. Curabitur vitae justo massa. Nulla nibh leo, imperdiet nec mauris euismod, ultrices pulvinar nulla. Duis eleifend, felis at cursus tincidunt, tortor nisl malesuada metus, sed posuere dolor arcu vestibulum ipsum. Proin semper vel metus non viverra. Suspendisse efficitur leo ac aliquet gravida. Aenean sit amet aliquet lorem, a condimentum erat. Maecenas porttitor neque sed eleifend euismod. Maecenas finibus purus ut metus laoreet aliquet. Cras eros purus, vulputate a libero sed, sodales posuere ipsum. Cras dolor diam, vehicula vitae eros a, semper semper neque. Suspendisse pulvinar est in orci ullamcorper, vitae porta velit commodo. Nam tempus elementum quam in convallis.",
		"Integer quis eleifend tellus, sit amet iaculis velit. Sed venenatis elit varius metus egestas volutpat. Sed mauris purus, malesuada gravida sagittis eu, dictum ut ante. Cras tincidunt, nunc et sodales elementum, felis neque vulputate tortor, ac hendrerit libero tellus sagittis arcu. Praesent vel tempor massa, et tempus quam. Nulla sollicitudin, augue quis vehicula vulputate, turpis ipsum facilisis tortor, in mattis dolor massa non metus. Mauris tincidunt lacus sit amet sem lobortis, et eleifend metus facilisis.",
		"Suspendisse metus mi, consequat ut porttitor ac, lobortis ut libero. Ut non nulla eleifend, sollicitudin neque id, fermentum metus. Mauris ac lectus nec nisi porttitor faucibus a tempus velit. Vestibulum feugiat ligula commodo, dictum turpis non, maximus justo. Integer non eros vel mauris tristique facilisis non eu urna. Morbi euismod eros libero, eget volutpat magna suscipit ac. In tempor odio ut maximus tristique. Donec vitae ligula ornare, pellentesque ligula eu, gravida justo. Duis dignissim elit sed erat commodo, a rutrum nisi dictum. Integer a dapibus risus. Nam tristique feugiat aliquam. Aliquam non massa faucibus, mollis lacus a, blandit leo.",
		"Donec hendrerit viverra ex ac molestie. In hendrerit porttitor nisi, eu auctor lectus ultrices pulvinar. Aliquam purus mauris, dapibus vel libero eu, accumsan eleifend lectus. Nullam pellentesque ut massa nec euismod. Nunc iaculis, velit eget bibendum fermentum, tortor sem rutrum dui, in molestie sem ante id magna. Curabitur ut tortor dignissim, consectetur metus dapibus, pharetra sapien. Duis lectus eros, convallis sit amet tincidunt nec, fermentum ac sem. Praesent iaculis urna quis posuere consectetur. Morbi et maximus nulla. Sed auctor imperdiet posuere. Vestibulum vel eros ac risus vehicula tincidunt. Proin porttitor metus vitae arcu pretium, ac sodales ex imperdiet. Curabitur fringilla nisl vitae neque mollis ultrices. Suspendisse id fermentum tortor. Aliquam pharetra metus at massa semper finibus. Phasellus sem urna, consectetur in volutpat sit amet, laoreet vitae tellus.",
		"Nunc commodo velit eu mollis fermentum. Suspendisse ut lacinia diam, et pharetra dolor. Nulla facilisi. Maecenas sed erat at diam dapibus molestie eget eu dui. Cras eu enim at nisi dapibus rutrum a eu sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam odio turpis, venenatis quis purus ut, sagittis convallis ipsum. Nam mattis pulvinar ultrices. Mauris velit sapien, suscipit nec arcu vitae, viverra mattis tortor. Duis quis scelerisque nibh. Proin vulputate porta risus, vel mattis velit posuere vitae. Quisque id libero dui. Fusce varius velit ut purus ornare, nec feugiat est convallis. Integer at feugiat diam."
		};
		
	}
	
	
	
	
}

